name: Build and deploy package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Add GitHub Packages Source
      run: |
          dotnet nuget add source https://nuget.pkg.github.com/osvaldoribeirodev/index.json -n github -u ${{ github.actor }} -p ${{ secrets.READ_GH_PACKAGES_PAT_ORG }} --store-password-in-clear-text
          dotnet restore ./MySecondPrivatePackage.sln
          dotnet build ./MySecondPrivatePackage.sln --no-restore --configuration Release --nologo
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    - name: Create the Package
      run: dotnet pack --configuration Release
    
    - name: Publish
      run: dotnet nuget push "bin/Release/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/osvaldoribeirodev/index.json --skip-duplicate